export type Ttab = "search" | "view" | "ask";

export type Tjob = {
  id?: number;
  name?: string;
  job_type?: string[];
  base_attack_speed?: string;
  secondary_weapon_power?: string;
  main_stat?: string[];
  sub_stat?: string;
  attack_power?: number;
  damage?: number;
  boss_damage?: number;
  final_damage?: number;
  defense_ignore?: number;
  attribute?: string[];
  additional_hit?: string;
  damage_distribution?: string;
  abnormal_status_resist?: number;
  all_attribute_resist?: number;
  super_stance?: string;
  mp_guard?: string;
  damage_reduction?: number;
  guard_possible?: string;
  critical_rate?: number;
  critical_damage?: number;
  skill_cost?: string;
  jump?: string;
  air_descent?: string;
  knock_back?: string;
  buff_disabled?: string;
  buff_removal?: string;
  self_bind?: string;
  invincibility?: number;
  resurrection?: string;
  death_prevention?: string;
  link_priority?: number;
  union_priority?: number;
  core_difficulty?: number;
};
