import { atom } from "recoil";

export const filterState = atom({
  key: "toggleFilter", // unique ID (with respect to other atoms/selectors)
  default: {
    name: null,
    job_type: [""],
    base_attack_speed: null,
    secondary_weapon_power: null,
    main_stat: [],
    sub_stat: null,
    attack_power: null,
    damage: null,
    boss_damage: null,
    final_damage: null,
    defense_ignore: null,
    attribute: [],
    additional_hit: null,
    damage_distribution: null,
    abnormal_status_resist: null,
    all_attribute_resist: null,
    super_stance: null,
    mp_guard: null,
    damage_reduction: null,
    guard_possible: null,
    critical_damage: null,
    critical_rate: null,
    skill_cost: null,
    jump: null,
    teleport: null,
    air_descent: null,
    knock_back: null,
    buff_disabled: null,
    buff_removal: null,
    self_bind: null,
    invincibility: null,
    resurrection: null,
    death_prevention: null,
    link_priority: null,
    union_priority: null,
    core_difficulty: null,
  },
});

// {
//     직업군: "",
//     "자력 풀공속": "",
//     "보조무기 강화": "",
//     주스탯: "",
//     부스탯: "",
//     속성: "",
//     "추가 타격": "",
//     풀스탠스: "",
//     "슈퍼 스탠스": "",
//     MP가드: "",
//     가드: "",
//     점프: "",
//     "공중 하강": "",
//     "버프 불능": "",
//     "버프 해제": "",
//     바인드: "",
//     무적: "",
//     "부활 및 사망 방지": "",
//   },
