export const JOB_NAMES: string[] = [
  "히어로",
  "팔라딘",
  "다크나이트",
  "소울마스터",
  "미하일",
  "블래스터",
  "데몬 슬레이어",
  "데몬 어벤져",
  "아란",
  "카이저",
  "아델",
  "제로",
  "아크메이지(불,독)",
  "아크메이지(썬,콜)",
  "비숍",
  "플레임위자드",
  "배틀메이지",
  "에반",
  "루미너스",
  "일리움",
  "라라",
  "키네시스",
  "보우마스터",
  "신궁",
  "패스파인더",
  "윈드브레이커",
  "와일드헌터",
  "메르세데스",
  "카인",
  "나이트로드",
  "섀도어",
  "듀얼블레이드",
  "나이트워커",
  "제논",
  "팬텀",
  "카데나",
  "칼리",
  "호영",
  "바이퍼",
  "캡틴",
  "캐논슈터",
  "스트라이커",
  "메카닉",
  "은월",
  "엔젤릭버스터",
  "아크",
];

export const TEXT_TO_IMAGE_DICT: {
  [key: string]: string;
} = {
  히어로: "char1",
  팔라딘: "char2",
  다크나이트: "char3",
  소울마스터: "char4",
  미하일: "char5",
  블래스터: "char6",
  "데몬 슬레이어": "char7",
  "데몬 어벤져": "char8",
  아란: "char9",
  카이저: "char10",
  아델: "char11",
  제로: "char12",
  "아크메이지(불,독)": "char13",
  "아크메이지(썬,콜)": "char14",
  비숍: "char15",
  플레임위자드: "char16",
  배틀메이지: "char17",
  에반: "char18",
  루미너스: "char19",
  일리움: "char20",
  라라: "char21",
  키네시스: "char22",
  보우마스터: "char23",
  신궁: "char24",
  패스파인더: "char25",
  윈드브레이커: "char26",
  와일드헌터: "char27",
  메르세데스: "char28",
  카인: "char29",
  나이트로드: "char30",
  섀도어: "char31",
  듀얼블레이드: "char32",
  나이트워커: "char33",
  제논: "char34",
  팬텀: "char35",
  카데나: "char36",
  칼리: "char37",
  호영: "char38",
  바이퍼: "char39",
  캡틴: "char40",
  캐논슈터: "char41",
  스트라이커: "char42",
  메카닉: "char43",
  은월: "char45",
  엔젤릭버스터: "char46",
  아크: "char47",
};

export const PROPERTY_TO_KR: {
  [key: string]: string;
} = {
  name: "이름",
  job_type: "직업군",
  base_attack_speed: "자력 풀공속",
  secondary_weapon_power: "보조무기 강화",
  main_stat: "주스탯",
  sub_stat: "부스탯",
  attack_power: "공마력",
  damage: "데미지",
  boss_damage: "보스데미지",
  final_damage: "최종데미지",
  defense_ignore: "방어력무시",
  attribute: "속성",
  additional_hit: "추가타격",
  damage_distribution: "데미지 분산",
  abnormal_status_resist: "상태 이상 내성",
  all_attribute_resist: "모든 속성 내성",
  super_stance: "슈퍼 스탠스",
  mp_guard: "MP 가드",
  damage_reduction: "최대 HP 비례 피해 감소",
  guard_possible: "가드 가능",
  critical_damage: "크리티컬 데미지",
  critical_rate: "크리티컬 확률",
  skill_cost: "스킬 코스트",
  jump: "점프",
  teleport: "순간이동",
  air_descent: "공중 하강",
  knock_back: "밀격/넉백",
  buff_disabled: "버프 불능",
  buff_removal: "버프 해제",
  self_bind: "자체 바인드",
  invincibility: "무적 시간",
  resurrection: "부활",
  death_prevention: "사망 방지",
  link_priority: "링크 우선 순위",
  union_priority: "유니온 우선 순위",
  core_difficulty: "코어 강화 난이도",
  job_role: "직업 역할",
};
